/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndServiceRouteImport } from './routes/terms-and-service'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as SpacesSocietiesRouteImport } from './routes/spaces/societies'
import { Route as SpacesSocialRouteImport } from './routes/spaces/social'
import { Route as SpacesPersonalRouteImport } from './routes/spaces/personal'
import { Route as SpacesCareerRouteImport } from './routes/spaces/career'
import { Route as SpacesAcademicsRouteImport } from './routes/spaces/academics'
import { Route as SocietiesSocietyIdRouteImport } from './routes/societies/$societyId'
import { Route as PeopleRequestsRouteImport } from './routes/people/requests'
import { Route as PeoplePeopleRouteImport } from './routes/people/people'
import { Route as JoinSocietySlugRouteImport } from './routes/join/$societySlug'
import { Route as AppsQueraRouteImport } from './routes/apps/quera'
import { Route as SpacesSocietiesIndexRouteImport } from './routes/spaces/societies/index'
import { Route as SpacesCareerIndexRouteImport } from './routes/spaces/career/index'
import { Route as SpacesAcademicsIndexRouteImport } from './routes/spaces/academics/index'
import { Route as JoinSocietySlugIndexRouteImport } from './routes/join/$societySlug/index'
import { Route as AppsQueraIndexRouteImport } from './routes/apps/quera/index'
import { Route as SpacesSocietiesMineRouteImport } from './routes/spaces/societies/mine'
import { Route as SpacesSocietiesCreateRouteImport } from './routes/spaces/societies/create'
import { Route as SpacesSocietiesCampusFeedRouteImport } from './routes/spaces/societies/campus-feed'
import { Route as SpacesCareerTuitionRouteImport } from './routes/spaces/career/tuition'
import { Route as SpacesCareerResumeBuilderRouteImport } from './routes/spaces/career/resume-builder'
import { Route as SpacesCareerInternshipRouteImport } from './routes/spaces/career/internship'
import { Route as SpacesCareerApplicationsRouteImport } from './routes/spaces/career/applications'
import { Route as SpacesAcademicsStudyGroupsRouteImport } from './routes/spaces/academics/study-groups'
import { Route as SpacesAcademicsOnboardingRouteImport } from './routes/spaces/academics/onboarding'
import { Route as SpacesAcademicsDashboardRouteImport } from './routes/spaces/academics/dashboard'
import { Route as JoinSocietySlugPaymentRouteImport } from './routes/join/$societySlug/payment'
import { Route as JoinSocietySlugApplyRouteImport } from './routes/join/$societySlug/apply'
import { Route as AppsQueraBuildRouteImport } from './routes/apps/quera/build'
import { Route as SpacesSocietiesMineIndexRouteImport } from './routes/spaces/societies/mine/index'
import { Route as SpacesSocietiesCampusFeedIndexRouteImport } from './routes/spaces/societies/campus-feed/index'
import { Route as SpacesSocietiesMineClubIDRouteImport } from './routes/spaces/societies/mine/$clubID'
import { Route as SpacesSocietiesDiscoverNetworkRouteImport } from './routes/spaces/societies/discover/network'
import { Route as SpacesSocietiesDiscoverEventsRouteImport } from './routes/spaces/societies/discover/events'
import { Route as SpacesSocietiesDiscoverBrowseClubsRouteImport } from './routes/spaces/societies/discover/browse-clubs'
import { Route as SpacesCareerResumeBuilderResumeidRouteImport } from './routes/spaces/career/resume-builder/$resumeid'
import { Route as SpacesCareerApplicationsIdRouteImport } from './routes/spaces/career/applications/$id'
import { Route as SpacesAcademicsDiscoverStudyGroupsRouteImport } from './routes/spaces/academics/discover/study-groups'
import { Route as SpacesAcademicsDiscoverStudyBuddyRouteImport } from './routes/spaces/academics/discover/study-buddy'
import { Route as SpacesAcademicsCoursesCourseIdRouteImport } from './routes/spaces/academics/courses/$courseId'
import { Route as AppsQueraPlayIdRouteImport } from './routes/apps/quera/play/$id'
import { Route as SpacesSocietiesMineClubIDIndexRouteImport } from './routes/spaces/societies/mine/$clubID/index'
import { Route as SpacesAcademicsCoursesCourseIdIndexRouteImport } from './routes/spaces/academics/courses/$courseId/index'
import { Route as SpacesSocietiesMineClubIDTeamsRouteImport } from './routes/spaces/societies/mine/$clubID/teams'
import { Route as SpacesSocietiesMineClubIDTasksRouteImport } from './routes/spaces/societies/mine/$clubID/tasks'
import { Route as SpacesSocietiesMineClubIDSettingsRouteImport } from './routes/spaces/societies/mine/$clubID/settings'
import { Route as SpacesSocietiesMineClubIDOnboardingRouteImport } from './routes/spaces/societies/mine/$clubID/onboarding'
import { Route as SpacesSocietiesMineClubIDMembersRouteImport } from './routes/spaces/societies/mine/$clubID/members'
import { Route as SpacesSocietiesMineClubIDJoinRequestsRouteImport } from './routes/spaces/societies/mine/$clubID/join-requests'
import { Route as SpacesSocietiesMineClubIDFormsRouteImport } from './routes/spaces/societies/mine/$clubID/forms'
import { Route as SpacesSocietiesMineClubIDExpensesRouteImport } from './routes/spaces/societies/mine/$clubID/expenses'
import { Route as SpacesSocietiesMineClubIDEmailRouteImport } from './routes/spaces/societies/mine/$clubID/email'
import { Route as SpacesSocietiesMineClubIDDiscussionRouteImport } from './routes/spaces/societies/mine/$clubID/discussion'
import { Route as SpacesAcademicsCoursesCourseIdDiscussionsRouteImport } from './routes/spaces/academics/courses/$courseId/discussions'
import { Route as SpacesSocietiesMineClubIDFormsIndexRouteImport } from './routes/spaces/societies/mine/$clubID/forms/index'
import { Route as SpacesSocietiesMineClubIDJoinRequestsRequestIdRouteImport } from './routes/spaces/societies/mine/$clubID/join-requests/$requestId'
import { Route as SpacesSocietiesMineClubIDFormsCreateRouteImport } from './routes/spaces/societies/mine/$clubID/forms/create'
import { Route as SpacesSocietiesMineClubIDFormsFormIdRouteImport } from './routes/spaces/societies/mine/$clubID/forms/$formId'

const TermsAndServiceRoute = TermsAndServiceRouteImport.update({
  id: '/terms-and-service',
  path: '/terms-and-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRoute,
} as any)
const SpacesSocietiesRoute = SpacesSocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesSocialRoute = SpacesSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesPersonalRoute = SpacesPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesCareerRoute = SpacesCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesAcademicsRoute = SpacesAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => SpacesRoute,
} as any)
const SocietiesSocietyIdRoute = SocietiesSocietyIdRouteImport.update({
  id: '/societies/$societyId',
  path: '/societies/$societyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRequestsRoute = PeopleRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PeopleRoute,
} as any)
const PeoplePeopleRoute = PeoplePeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => PeopleRoute,
} as any)
const JoinSocietySlugRoute = JoinSocietySlugRouteImport.update({
  id: '/$societySlug',
  path: '/$societySlug',
  getParentRoute: () => JoinRoute,
} as any)
const AppsQueraRoute = AppsQueraRouteImport.update({
  id: '/quera',
  path: '/quera',
  getParentRoute: () => AppsRoute,
} as any)
const SpacesSocietiesIndexRoute = SpacesSocietiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesSocietiesRoute,
} as any)
const SpacesCareerIndexRoute = SpacesCareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesCareerRoute,
} as any)
const SpacesAcademicsIndexRoute = SpacesAcademicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesAcademicsRoute,
} as any)
const JoinSocietySlugIndexRoute = JoinSocietySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoinSocietySlugRoute,
} as any)
const AppsQueraIndexRoute = AppsQueraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsQueraRoute,
} as any)
const SpacesSocietiesMineRoute = SpacesSocietiesMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => SpacesSocietiesRoute,
} as any)
const SpacesSocietiesCreateRoute = SpacesSocietiesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SpacesSocietiesRoute,
} as any)
const SpacesSocietiesCampusFeedRoute =
  SpacesSocietiesCampusFeedRouteImport.update({
    id: '/campus-feed',
    path: '/campus-feed',
    getParentRoute: () => SpacesSocietiesRoute,
  } as any)
const SpacesCareerTuitionRoute = SpacesCareerTuitionRouteImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => SpacesCareerRoute,
} as any)
const SpacesCareerResumeBuilderRoute =
  SpacesCareerResumeBuilderRouteImport.update({
    id: '/resume-builder',
    path: '/resume-builder',
    getParentRoute: () => SpacesCareerRoute,
  } as any)
const SpacesCareerInternshipRoute = SpacesCareerInternshipRouteImport.update({
  id: '/internship',
  path: '/internship',
  getParentRoute: () => SpacesCareerRoute,
} as any)
const SpacesCareerApplicationsRoute =
  SpacesCareerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => SpacesCareerRoute,
  } as any)
const SpacesAcademicsStudyGroupsRoute =
  SpacesAcademicsStudyGroupsRouteImport.update({
    id: '/study-groups',
    path: '/study-groups',
    getParentRoute: () => SpacesAcademicsRoute,
  } as any)
const SpacesAcademicsOnboardingRoute =
  SpacesAcademicsOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => SpacesAcademicsRoute,
  } as any)
const SpacesAcademicsDashboardRoute =
  SpacesAcademicsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SpacesAcademicsRoute,
  } as any)
const JoinSocietySlugPaymentRoute = JoinSocietySlugPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => JoinSocietySlugRoute,
} as any)
const JoinSocietySlugApplyRoute = JoinSocietySlugApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JoinSocietySlugRoute,
} as any)
const AppsQueraBuildRoute = AppsQueraBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AppsQueraRoute,
} as any)
const SpacesSocietiesMineIndexRoute =
  SpacesSocietiesMineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SpacesSocietiesMineRoute,
  } as any)
const SpacesSocietiesCampusFeedIndexRoute =
  SpacesSocietiesCampusFeedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SpacesSocietiesCampusFeedRoute,
  } as any)
const SpacesSocietiesMineClubIDRoute =
  SpacesSocietiesMineClubIDRouteImport.update({
    id: '/$clubID',
    path: '/$clubID',
    getParentRoute: () => SpacesSocietiesMineRoute,
  } as any)
const SpacesSocietiesDiscoverNetworkRoute =
  SpacesSocietiesDiscoverNetworkRouteImport.update({
    id: '/discover/network',
    path: '/discover/network',
    getParentRoute: () => SpacesSocietiesRoute,
  } as any)
const SpacesSocietiesDiscoverEventsRoute =
  SpacesSocietiesDiscoverEventsRouteImport.update({
    id: '/discover/events',
    path: '/discover/events',
    getParentRoute: () => SpacesSocietiesRoute,
  } as any)
const SpacesSocietiesDiscoverBrowseClubsRoute =
  SpacesSocietiesDiscoverBrowseClubsRouteImport.update({
    id: '/discover/browse-clubs',
    path: '/discover/browse-clubs',
    getParentRoute: () => SpacesSocietiesRoute,
  } as any)
const SpacesCareerResumeBuilderResumeidRoute =
  SpacesCareerResumeBuilderResumeidRouteImport.update({
    id: '/$resumeid',
    path: '/$resumeid',
    getParentRoute: () => SpacesCareerResumeBuilderRoute,
  } as any)
const SpacesCareerApplicationsIdRoute =
  SpacesCareerApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => SpacesCareerApplicationsRoute,
  } as any)
const SpacesAcademicsDiscoverStudyGroupsRoute =
  SpacesAcademicsDiscoverStudyGroupsRouteImport.update({
    id: '/discover/study-groups',
    path: '/discover/study-groups',
    getParentRoute: () => SpacesAcademicsRoute,
  } as any)
const SpacesAcademicsDiscoverStudyBuddyRoute =
  SpacesAcademicsDiscoverStudyBuddyRouteImport.update({
    id: '/discover/study-buddy',
    path: '/discover/study-buddy',
    getParentRoute: () => SpacesAcademicsRoute,
  } as any)
const SpacesAcademicsCoursesCourseIdRoute =
  SpacesAcademicsCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => SpacesAcademicsRoute,
  } as any)
const AppsQueraPlayIdRoute = AppsQueraPlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => AppsQueraRoute,
} as any)
const SpacesSocietiesMineClubIDIndexRoute =
  SpacesSocietiesMineClubIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesAcademicsCoursesCourseIdIndexRoute =
  SpacesAcademicsCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SpacesAcademicsCoursesCourseIdRoute,
  } as any)
const SpacesSocietiesMineClubIDTeamsRoute =
  SpacesSocietiesMineClubIDTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDTasksRoute =
  SpacesSocietiesMineClubIDTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDSettingsRoute =
  SpacesSocietiesMineClubIDSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDOnboardingRoute =
  SpacesSocietiesMineClubIDOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDMembersRoute =
  SpacesSocietiesMineClubIDMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDJoinRequestsRoute =
  SpacesSocietiesMineClubIDJoinRequestsRouteImport.update({
    id: '/join-requests',
    path: '/join-requests',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDFormsRoute =
  SpacesSocietiesMineClubIDFormsRouteImport.update({
    id: '/forms',
    path: '/forms',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDExpensesRoute =
  SpacesSocietiesMineClubIDExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDEmailRoute =
  SpacesSocietiesMineClubIDEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesSocietiesMineClubIDDiscussionRoute =
  SpacesSocietiesMineClubIDDiscussionRouteImport.update({
    id: '/discussion',
    path: '/discussion',
    getParentRoute: () => SpacesSocietiesMineClubIDRoute,
  } as any)
const SpacesAcademicsCoursesCourseIdDiscussionsRoute =
  SpacesAcademicsCoursesCourseIdDiscussionsRouteImport.update({
    id: '/discussions',
    path: '/discussions',
    getParentRoute: () => SpacesAcademicsCoursesCourseIdRoute,
  } as any)
const SpacesSocietiesMineClubIDFormsIndexRoute =
  SpacesSocietiesMineClubIDFormsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SpacesSocietiesMineClubIDFormsRoute,
  } as any)
const SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute =
  SpacesSocietiesMineClubIDJoinRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => SpacesSocietiesMineClubIDJoinRequestsRoute,
  } as any)
const SpacesSocietiesMineClubIDFormsCreateRoute =
  SpacesSocietiesMineClubIDFormsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => SpacesSocietiesMineClubIDFormsRoute,
  } as any)
const SpacesSocietiesMineClubIDFormsFormIdRoute =
  SpacesSocietiesMineClubIDFormsFormIdRouteImport.update({
    id: '/$formId',
    path: '/$formId',
    getParentRoute: () => SpacesSocietiesMineClubIDFormsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/apps': typeof AppsRouteWithChildren
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/people': typeof PeopleRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/terms-and-service': typeof TermsAndServiceRoute
  '/apps/quera': typeof AppsQueraRouteWithChildren
  '/join/$societySlug': typeof JoinSocietySlugRouteWithChildren
  '/people/people': typeof PeoplePeopleRoute
  '/people/requests': typeof PeopleRequestsRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/spaces/academics': typeof SpacesAcademicsRouteWithChildren
  '/spaces/career': typeof SpacesCareerRouteWithChildren
  '/spaces/personal': typeof SpacesPersonalRoute
  '/spaces/social': typeof SpacesSocialRoute
  '/spaces/societies': typeof SpacesSocietiesRouteWithChildren
  '/$username/': typeof UsernameIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/apps/quera/build': typeof AppsQueraBuildRoute
  '/join/$societySlug/apply': typeof JoinSocietySlugApplyRoute
  '/join/$societySlug/payment': typeof JoinSocietySlugPaymentRoute
  '/spaces/academics/dashboard': typeof SpacesAcademicsDashboardRoute
  '/spaces/academics/onboarding': typeof SpacesAcademicsOnboardingRoute
  '/spaces/academics/study-groups': typeof SpacesAcademicsStudyGroupsRoute
  '/spaces/career/applications': typeof SpacesCareerApplicationsRouteWithChildren
  '/spaces/career/internship': typeof SpacesCareerInternshipRoute
  '/spaces/career/resume-builder': typeof SpacesCareerResumeBuilderRouteWithChildren
  '/spaces/career/tuition': typeof SpacesCareerTuitionRoute
  '/spaces/societies/campus-feed': typeof SpacesSocietiesCampusFeedRouteWithChildren
  '/spaces/societies/create': typeof SpacesSocietiesCreateRoute
  '/spaces/societies/mine': typeof SpacesSocietiesMineRouteWithChildren
  '/apps/quera/': typeof AppsQueraIndexRoute
  '/join/$societySlug/': typeof JoinSocietySlugIndexRoute
  '/spaces/academics/': typeof SpacesAcademicsIndexRoute
  '/spaces/career/': typeof SpacesCareerIndexRoute
  '/spaces/societies/': typeof SpacesSocietiesIndexRoute
  '/apps/quera/play/$id': typeof AppsQueraPlayIdRoute
  '/spaces/academics/courses/$courseId': typeof SpacesAcademicsCoursesCourseIdRouteWithChildren
  '/spaces/academics/discover/study-buddy': typeof SpacesAcademicsDiscoverStudyBuddyRoute
  '/spaces/academics/discover/study-groups': typeof SpacesAcademicsDiscoverStudyGroupsRoute
  '/spaces/career/applications/$id': typeof SpacesCareerApplicationsIdRoute
  '/spaces/career/resume-builder/$resumeid': typeof SpacesCareerResumeBuilderResumeidRoute
  '/spaces/societies/discover/browse-clubs': typeof SpacesSocietiesDiscoverBrowseClubsRoute
  '/spaces/societies/discover/events': typeof SpacesSocietiesDiscoverEventsRoute
  '/spaces/societies/discover/network': typeof SpacesSocietiesDiscoverNetworkRoute
  '/spaces/societies/mine/$clubID': typeof SpacesSocietiesMineClubIDRouteWithChildren
  '/spaces/societies/campus-feed/': typeof SpacesSocietiesCampusFeedIndexRoute
  '/spaces/societies/mine/': typeof SpacesSocietiesMineIndexRoute
  '/spaces/academics/courses/$courseId/discussions': typeof SpacesAcademicsCoursesCourseIdDiscussionsRoute
  '/spaces/societies/mine/$clubID/discussion': typeof SpacesSocietiesMineClubIDDiscussionRoute
  '/spaces/societies/mine/$clubID/email': typeof SpacesSocietiesMineClubIDEmailRoute
  '/spaces/societies/mine/$clubID/expenses': typeof SpacesSocietiesMineClubIDExpensesRoute
  '/spaces/societies/mine/$clubID/forms': typeof SpacesSocietiesMineClubIDFormsRouteWithChildren
  '/spaces/societies/mine/$clubID/join-requests': typeof SpacesSocietiesMineClubIDJoinRequestsRouteWithChildren
  '/spaces/societies/mine/$clubID/members': typeof SpacesSocietiesMineClubIDMembersRoute
  '/spaces/societies/mine/$clubID/onboarding': typeof SpacesSocietiesMineClubIDOnboardingRoute
  '/spaces/societies/mine/$clubID/settings': typeof SpacesSocietiesMineClubIDSettingsRoute
  '/spaces/societies/mine/$clubID/tasks': typeof SpacesSocietiesMineClubIDTasksRoute
  '/spaces/societies/mine/$clubID/teams': typeof SpacesSocietiesMineClubIDTeamsRoute
  '/spaces/academics/courses/$courseId/': typeof SpacesAcademicsCoursesCourseIdIndexRoute
  '/spaces/societies/mine/$clubID/': typeof SpacesSocietiesMineClubIDIndexRoute
  '/spaces/societies/mine/$clubID/forms/$formId': typeof SpacesSocietiesMineClubIDFormsFormIdRoute
  '/spaces/societies/mine/$clubID/forms/create': typeof SpacesSocietiesMineClubIDFormsCreateRoute
  '/spaces/societies/mine/$clubID/join-requests/$requestId': typeof SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute
  '/spaces/societies/mine/$clubID/forms/': typeof SpacesSocietiesMineClubIDFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/terms-and-service': typeof TermsAndServiceRoute
  '/people/people': typeof PeoplePeopleRoute
  '/people/requests': typeof PeopleRequestsRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/spaces/personal': typeof SpacesPersonalRoute
  '/spaces/social': typeof SpacesSocialRoute
  '/$username': typeof UsernameIndexRoute
  '/people': typeof PeopleIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/apps/quera/build': typeof AppsQueraBuildRoute
  '/join/$societySlug/apply': typeof JoinSocietySlugApplyRoute
  '/join/$societySlug/payment': typeof JoinSocietySlugPaymentRoute
  '/spaces/academics/dashboard': typeof SpacesAcademicsDashboardRoute
  '/spaces/academics/onboarding': typeof SpacesAcademicsOnboardingRoute
  '/spaces/academics/study-groups': typeof SpacesAcademicsStudyGroupsRoute
  '/spaces/career/applications': typeof SpacesCareerApplicationsRouteWithChildren
  '/spaces/career/internship': typeof SpacesCareerInternshipRoute
  '/spaces/career/resume-builder': typeof SpacesCareerResumeBuilderRouteWithChildren
  '/spaces/career/tuition': typeof SpacesCareerTuitionRoute
  '/spaces/societies/create': typeof SpacesSocietiesCreateRoute
  '/apps/quera': typeof AppsQueraIndexRoute
  '/join/$societySlug': typeof JoinSocietySlugIndexRoute
  '/spaces/academics': typeof SpacesAcademicsIndexRoute
  '/spaces/career': typeof SpacesCareerIndexRoute
  '/spaces/societies': typeof SpacesSocietiesIndexRoute
  '/apps/quera/play/$id': typeof AppsQueraPlayIdRoute
  '/spaces/academics/discover/study-buddy': typeof SpacesAcademicsDiscoverStudyBuddyRoute
  '/spaces/academics/discover/study-groups': typeof SpacesAcademicsDiscoverStudyGroupsRoute
  '/spaces/career/applications/$id': typeof SpacesCareerApplicationsIdRoute
  '/spaces/career/resume-builder/$resumeid': typeof SpacesCareerResumeBuilderResumeidRoute
  '/spaces/societies/discover/browse-clubs': typeof SpacesSocietiesDiscoverBrowseClubsRoute
  '/spaces/societies/discover/events': typeof SpacesSocietiesDiscoverEventsRoute
  '/spaces/societies/discover/network': typeof SpacesSocietiesDiscoverNetworkRoute
  '/spaces/societies/campus-feed': typeof SpacesSocietiesCampusFeedIndexRoute
  '/spaces/societies/mine': typeof SpacesSocietiesMineIndexRoute
  '/spaces/academics/courses/$courseId/discussions': typeof SpacesAcademicsCoursesCourseIdDiscussionsRoute
  '/spaces/societies/mine/$clubID/discussion': typeof SpacesSocietiesMineClubIDDiscussionRoute
  '/spaces/societies/mine/$clubID/email': typeof SpacesSocietiesMineClubIDEmailRoute
  '/spaces/societies/mine/$clubID/expenses': typeof SpacesSocietiesMineClubIDExpensesRoute
  '/spaces/societies/mine/$clubID/join-requests': typeof SpacesSocietiesMineClubIDJoinRequestsRouteWithChildren
  '/spaces/societies/mine/$clubID/members': typeof SpacesSocietiesMineClubIDMembersRoute
  '/spaces/societies/mine/$clubID/onboarding': typeof SpacesSocietiesMineClubIDOnboardingRoute
  '/spaces/societies/mine/$clubID/settings': typeof SpacesSocietiesMineClubIDSettingsRoute
  '/spaces/societies/mine/$clubID/tasks': typeof SpacesSocietiesMineClubIDTasksRoute
  '/spaces/societies/mine/$clubID/teams': typeof SpacesSocietiesMineClubIDTeamsRoute
  '/spaces/academics/courses/$courseId': typeof SpacesAcademicsCoursesCourseIdIndexRoute
  '/spaces/societies/mine/$clubID': typeof SpacesSocietiesMineClubIDIndexRoute
  '/spaces/societies/mine/$clubID/forms/$formId': typeof SpacesSocietiesMineClubIDFormsFormIdRoute
  '/spaces/societies/mine/$clubID/forms/create': typeof SpacesSocietiesMineClubIDFormsCreateRoute
  '/spaces/societies/mine/$clubID/join-requests/$requestId': typeof SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute
  '/spaces/societies/mine/$clubID/forms': typeof SpacesSocietiesMineClubIDFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/apps': typeof AppsRouteWithChildren
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/people': typeof PeopleRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/terms-and-service': typeof TermsAndServiceRoute
  '/apps/quera': typeof AppsQueraRouteWithChildren
  '/join/$societySlug': typeof JoinSocietySlugRouteWithChildren
  '/people/people': typeof PeoplePeopleRoute
  '/people/requests': typeof PeopleRequestsRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/spaces/academics': typeof SpacesAcademicsRouteWithChildren
  '/spaces/career': typeof SpacesCareerRouteWithChildren
  '/spaces/personal': typeof SpacesPersonalRoute
  '/spaces/social': typeof SpacesSocialRoute
  '/spaces/societies': typeof SpacesSocietiesRouteWithChildren
  '/$username/': typeof UsernameIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/apps/quera/build': typeof AppsQueraBuildRoute
  '/join/$societySlug/apply': typeof JoinSocietySlugApplyRoute
  '/join/$societySlug/payment': typeof JoinSocietySlugPaymentRoute
  '/spaces/academics/dashboard': typeof SpacesAcademicsDashboardRoute
  '/spaces/academics/onboarding': typeof SpacesAcademicsOnboardingRoute
  '/spaces/academics/study-groups': typeof SpacesAcademicsStudyGroupsRoute
  '/spaces/career/applications': typeof SpacesCareerApplicationsRouteWithChildren
  '/spaces/career/internship': typeof SpacesCareerInternshipRoute
  '/spaces/career/resume-builder': typeof SpacesCareerResumeBuilderRouteWithChildren
  '/spaces/career/tuition': typeof SpacesCareerTuitionRoute
  '/spaces/societies/campus-feed': typeof SpacesSocietiesCampusFeedRouteWithChildren
  '/spaces/societies/create': typeof SpacesSocietiesCreateRoute
  '/spaces/societies/mine': typeof SpacesSocietiesMineRouteWithChildren
  '/apps/quera/': typeof AppsQueraIndexRoute
  '/join/$societySlug/': typeof JoinSocietySlugIndexRoute
  '/spaces/academics/': typeof SpacesAcademicsIndexRoute
  '/spaces/career/': typeof SpacesCareerIndexRoute
  '/spaces/societies/': typeof SpacesSocietiesIndexRoute
  '/apps/quera/play/$id': typeof AppsQueraPlayIdRoute
  '/spaces/academics/courses/$courseId': typeof SpacesAcademicsCoursesCourseIdRouteWithChildren
  '/spaces/academics/discover/study-buddy': typeof SpacesAcademicsDiscoverStudyBuddyRoute
  '/spaces/academics/discover/study-groups': typeof SpacesAcademicsDiscoverStudyGroupsRoute
  '/spaces/career/applications/$id': typeof SpacesCareerApplicationsIdRoute
  '/spaces/career/resume-builder/$resumeid': typeof SpacesCareerResumeBuilderResumeidRoute
  '/spaces/societies/discover/browse-clubs': typeof SpacesSocietiesDiscoverBrowseClubsRoute
  '/spaces/societies/discover/events': typeof SpacesSocietiesDiscoverEventsRoute
  '/spaces/societies/discover/network': typeof SpacesSocietiesDiscoverNetworkRoute
  '/spaces/societies/mine/$clubID': typeof SpacesSocietiesMineClubIDRouteWithChildren
  '/spaces/societies/campus-feed/': typeof SpacesSocietiesCampusFeedIndexRoute
  '/spaces/societies/mine/': typeof SpacesSocietiesMineIndexRoute
  '/spaces/academics/courses/$courseId/discussions': typeof SpacesAcademicsCoursesCourseIdDiscussionsRoute
  '/spaces/societies/mine/$clubID/discussion': typeof SpacesSocietiesMineClubIDDiscussionRoute
  '/spaces/societies/mine/$clubID/email': typeof SpacesSocietiesMineClubIDEmailRoute
  '/spaces/societies/mine/$clubID/expenses': typeof SpacesSocietiesMineClubIDExpensesRoute
  '/spaces/societies/mine/$clubID/forms': typeof SpacesSocietiesMineClubIDFormsRouteWithChildren
  '/spaces/societies/mine/$clubID/join-requests': typeof SpacesSocietiesMineClubIDJoinRequestsRouteWithChildren
  '/spaces/societies/mine/$clubID/members': typeof SpacesSocietiesMineClubIDMembersRoute
  '/spaces/societies/mine/$clubID/onboarding': typeof SpacesSocietiesMineClubIDOnboardingRoute
  '/spaces/societies/mine/$clubID/settings': typeof SpacesSocietiesMineClubIDSettingsRoute
  '/spaces/societies/mine/$clubID/tasks': typeof SpacesSocietiesMineClubIDTasksRoute
  '/spaces/societies/mine/$clubID/teams': typeof SpacesSocietiesMineClubIDTeamsRoute
  '/spaces/academics/courses/$courseId/': typeof SpacesAcademicsCoursesCourseIdIndexRoute
  '/spaces/societies/mine/$clubID/': typeof SpacesSocietiesMineClubIDIndexRoute
  '/spaces/societies/mine/$clubID/forms/$formId': typeof SpacesSocietiesMineClubIDFormsFormIdRoute
  '/spaces/societies/mine/$clubID/forms/create': typeof SpacesSocietiesMineClubIDFormsCreateRoute
  '/spaces/societies/mine/$clubID/join-requests/$requestId': typeof SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute
  '/spaces/societies/mine/$clubID/forms/': typeof SpacesSocietiesMineClubIDFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/apps'
    | '/join'
    | '/login'
    | '/not-found'
    | '/people'
    | '/privacy-policy'
    | '/profile'
    | '/roadmap'
    | '/signup'
    | '/spaces'
    | '/terms-and-service'
    | '/apps/quera'
    | '/join/$societySlug'
    | '/people/people'
    | '/people/requests'
    | '/societies/$societyId'
    | '/spaces/academics'
    | '/spaces/career'
    | '/spaces/personal'
    | '/spaces/social'
    | '/spaces/societies'
    | '/$username/'
    | '/people/'
    | '/profile/'
    | '/spaces/'
    | '/apps/quera/build'
    | '/join/$societySlug/apply'
    | '/join/$societySlug/payment'
    | '/spaces/academics/dashboard'
    | '/spaces/academics/onboarding'
    | '/spaces/academics/study-groups'
    | '/spaces/career/applications'
    | '/spaces/career/internship'
    | '/spaces/career/resume-builder'
    | '/spaces/career/tuition'
    | '/spaces/societies/campus-feed'
    | '/spaces/societies/create'
    | '/spaces/societies/mine'
    | '/apps/quera/'
    | '/join/$societySlug/'
    | '/spaces/academics/'
    | '/spaces/career/'
    | '/spaces/societies/'
    | '/apps/quera/play/$id'
    | '/spaces/academics/courses/$courseId'
    | '/spaces/academics/discover/study-buddy'
    | '/spaces/academics/discover/study-groups'
    | '/spaces/career/applications/$id'
    | '/spaces/career/resume-builder/$resumeid'
    | '/spaces/societies/discover/browse-clubs'
    | '/spaces/societies/discover/events'
    | '/spaces/societies/discover/network'
    | '/spaces/societies/mine/$clubID'
    | '/spaces/societies/campus-feed/'
    | '/spaces/societies/mine/'
    | '/spaces/academics/courses/$courseId/discussions'
    | '/spaces/societies/mine/$clubID/discussion'
    | '/spaces/societies/mine/$clubID/email'
    | '/spaces/societies/mine/$clubID/expenses'
    | '/spaces/societies/mine/$clubID/forms'
    | '/spaces/societies/mine/$clubID/join-requests'
    | '/spaces/societies/mine/$clubID/members'
    | '/spaces/societies/mine/$clubID/onboarding'
    | '/spaces/societies/mine/$clubID/settings'
    | '/spaces/societies/mine/$clubID/tasks'
    | '/spaces/societies/mine/$clubID/teams'
    | '/spaces/academics/courses/$courseId/'
    | '/spaces/societies/mine/$clubID/'
    | '/spaces/societies/mine/$clubID/forms/$formId'
    | '/spaces/societies/mine/$clubID/forms/create'
    | '/spaces/societies/mine/$clubID/join-requests/$requestId'
    | '/spaces/societies/mine/$clubID/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/join'
    | '/login'
    | '/not-found'
    | '/privacy-policy'
    | '/roadmap'
    | '/signup'
    | '/terms-and-service'
    | '/people/people'
    | '/people/requests'
    | '/societies/$societyId'
    | '/spaces/personal'
    | '/spaces/social'
    | '/$username'
    | '/people'
    | '/profile'
    | '/spaces'
    | '/apps/quera/build'
    | '/join/$societySlug/apply'
    | '/join/$societySlug/payment'
    | '/spaces/academics/dashboard'
    | '/spaces/academics/onboarding'
    | '/spaces/academics/study-groups'
    | '/spaces/career/applications'
    | '/spaces/career/internship'
    | '/spaces/career/resume-builder'
    | '/spaces/career/tuition'
    | '/spaces/societies/create'
    | '/apps/quera'
    | '/join/$societySlug'
    | '/spaces/academics'
    | '/spaces/career'
    | '/spaces/societies'
    | '/apps/quera/play/$id'
    | '/spaces/academics/discover/study-buddy'
    | '/spaces/academics/discover/study-groups'
    | '/spaces/career/applications/$id'
    | '/spaces/career/resume-builder/$resumeid'
    | '/spaces/societies/discover/browse-clubs'
    | '/spaces/societies/discover/events'
    | '/spaces/societies/discover/network'
    | '/spaces/societies/campus-feed'
    | '/spaces/societies/mine'
    | '/spaces/academics/courses/$courseId/discussions'
    | '/spaces/societies/mine/$clubID/discussion'
    | '/spaces/societies/mine/$clubID/email'
    | '/spaces/societies/mine/$clubID/expenses'
    | '/spaces/societies/mine/$clubID/join-requests'
    | '/spaces/societies/mine/$clubID/members'
    | '/spaces/societies/mine/$clubID/onboarding'
    | '/spaces/societies/mine/$clubID/settings'
    | '/spaces/societies/mine/$clubID/tasks'
    | '/spaces/societies/mine/$clubID/teams'
    | '/spaces/academics/courses/$courseId'
    | '/spaces/societies/mine/$clubID'
    | '/spaces/societies/mine/$clubID/forms/$formId'
    | '/spaces/societies/mine/$clubID/forms/create'
    | '/spaces/societies/mine/$clubID/join-requests/$requestId'
    | '/spaces/societies/mine/$clubID/forms'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/apps'
    | '/join'
    | '/login'
    | '/not-found'
    | '/people'
    | '/privacy-policy'
    | '/profile'
    | '/roadmap'
    | '/signup'
    | '/spaces'
    | '/terms-and-service'
    | '/apps/quera'
    | '/join/$societySlug'
    | '/people/people'
    | '/people/requests'
    | '/societies/$societyId'
    | '/spaces/academics'
    | '/spaces/career'
    | '/spaces/personal'
    | '/spaces/social'
    | '/spaces/societies'
    | '/$username/'
    | '/people/'
    | '/profile/'
    | '/spaces/'
    | '/apps/quera/build'
    | '/join/$societySlug/apply'
    | '/join/$societySlug/payment'
    | '/spaces/academics/dashboard'
    | '/spaces/academics/onboarding'
    | '/spaces/academics/study-groups'
    | '/spaces/career/applications'
    | '/spaces/career/internship'
    | '/spaces/career/resume-builder'
    | '/spaces/career/tuition'
    | '/spaces/societies/campus-feed'
    | '/spaces/societies/create'
    | '/spaces/societies/mine'
    | '/apps/quera/'
    | '/join/$societySlug/'
    | '/spaces/academics/'
    | '/spaces/career/'
    | '/spaces/societies/'
    | '/apps/quera/play/$id'
    | '/spaces/academics/courses/$courseId'
    | '/spaces/academics/discover/study-buddy'
    | '/spaces/academics/discover/study-groups'
    | '/spaces/career/applications/$id'
    | '/spaces/career/resume-builder/$resumeid'
    | '/spaces/societies/discover/browse-clubs'
    | '/spaces/societies/discover/events'
    | '/spaces/societies/discover/network'
    | '/spaces/societies/mine/$clubID'
    | '/spaces/societies/campus-feed/'
    | '/spaces/societies/mine/'
    | '/spaces/academics/courses/$courseId/discussions'
    | '/spaces/societies/mine/$clubID/discussion'
    | '/spaces/societies/mine/$clubID/email'
    | '/spaces/societies/mine/$clubID/expenses'
    | '/spaces/societies/mine/$clubID/forms'
    | '/spaces/societies/mine/$clubID/join-requests'
    | '/spaces/societies/mine/$clubID/members'
    | '/spaces/societies/mine/$clubID/onboarding'
    | '/spaces/societies/mine/$clubID/settings'
    | '/spaces/societies/mine/$clubID/tasks'
    | '/spaces/societies/mine/$clubID/teams'
    | '/spaces/academics/courses/$courseId/'
    | '/spaces/societies/mine/$clubID/'
    | '/spaces/societies/mine/$clubID/forms/$formId'
    | '/spaces/societies/mine/$clubID/forms/create'
    | '/spaces/societies/mine/$clubID/join-requests/$requestId'
    | '/spaces/societies/mine/$clubID/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRouteWithChildren
  AppsRoute: typeof AppsRouteWithChildren
  JoinRoute: typeof JoinRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  SignupRoute: typeof SignupRoute
  SpacesRoute: typeof SpacesRouteWithChildren
  TermsAndServiceRoute: typeof TermsAndServiceRoute
  SocietiesSocietyIdRoute: typeof SocietiesSocietyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-service': {
      id: '/terms-and-service'
      path: '/terms-and-service'
      fullPath: '/terms-and-service'
      preLoaderRoute: typeof TermsAndServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/$username/': {
      id: '/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/spaces/societies': {
      id: '/spaces/societies'
      path: '/societies'
      fullPath: '/spaces/societies'
      preLoaderRoute: typeof SpacesSocietiesRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/social': {
      id: '/spaces/social'
      path: '/social'
      fullPath: '/spaces/social'
      preLoaderRoute: typeof SpacesSocialRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/personal': {
      id: '/spaces/personal'
      path: '/personal'
      fullPath: '/spaces/personal'
      preLoaderRoute: typeof SpacesPersonalRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/career': {
      id: '/spaces/career'
      path: '/career'
      fullPath: '/spaces/career'
      preLoaderRoute: typeof SpacesCareerRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/academics': {
      id: '/spaces/academics'
      path: '/academics'
      fullPath: '/spaces/academics'
      preLoaderRoute: typeof SpacesAcademicsRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/societies/$societyId': {
      id: '/societies/$societyId'
      path: '/societies/$societyId'
      fullPath: '/societies/$societyId'
      preLoaderRoute: typeof SocietiesSocietyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/requests': {
      id: '/people/requests'
      path: '/requests'
      fullPath: '/people/requests'
      preLoaderRoute: typeof PeopleRequestsRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/people': {
      id: '/people/people'
      path: '/people'
      fullPath: '/people/people'
      preLoaderRoute: typeof PeoplePeopleRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/join/$societySlug': {
      id: '/join/$societySlug'
      path: '/$societySlug'
      fullPath: '/join/$societySlug'
      preLoaderRoute: typeof JoinSocietySlugRouteImport
      parentRoute: typeof JoinRoute
    }
    '/apps/quera': {
      id: '/apps/quera'
      path: '/quera'
      fullPath: '/apps/quera'
      preLoaderRoute: typeof AppsQueraRouteImport
      parentRoute: typeof AppsRoute
    }
    '/spaces/societies/': {
      id: '/spaces/societies/'
      path: '/'
      fullPath: '/spaces/societies/'
      preLoaderRoute: typeof SpacesSocietiesIndexRouteImport
      parentRoute: typeof SpacesSocietiesRoute
    }
    '/spaces/career/': {
      id: '/spaces/career/'
      path: '/'
      fullPath: '/spaces/career/'
      preLoaderRoute: typeof SpacesCareerIndexRouteImport
      parentRoute: typeof SpacesCareerRoute
    }
    '/spaces/academics/': {
      id: '/spaces/academics/'
      path: '/'
      fullPath: '/spaces/academics/'
      preLoaderRoute: typeof SpacesAcademicsIndexRouteImport
      parentRoute: typeof SpacesAcademicsRoute
    }
    '/join/$societySlug/': {
      id: '/join/$societySlug/'
      path: '/'
      fullPath: '/join/$societySlug/'
      preLoaderRoute: typeof JoinSocietySlugIndexRouteImport
      parentRoute: typeof JoinSocietySlugRoute
    }
    '/apps/quera/': {
      id: '/apps/quera/'
      path: '/'
      fullPath: '/apps/quera/'
      preLoaderRoute: typeof AppsQueraIndexRouteImport
      parentRoute: typeof AppsQueraRoute
    }
    '/spaces/societies/mine': {
      id: '/spaces/societies/mine'
      path: '/mine'
      fullPath: '/spaces/societies/mine'
      preLoaderRoute: typeof SpacesSocietiesMineRouteImport
      parentRoute: typeof SpacesSocietiesRoute
    }
    '/spaces/societies/create': {
      id: '/spaces/societies/create'
      path: '/create'
      fullPath: '/spaces/societies/create'
      preLoaderRoute: typeof SpacesSocietiesCreateRouteImport
      parentRoute: typeof SpacesSocietiesRoute
    }
    '/spaces/societies/campus-feed': {
      id: '/spaces/societies/campus-feed'
      path: '/campus-feed'
      fullPath: '/spaces/societies/campus-feed'
      preLoaderRoute: typeof SpacesSocietiesCampusFeedRouteImport
      parentRoute: typeof SpacesSocietiesRoute
    }
    '/spaces/career/tuition': {
      id: '/spaces/career/tuition'
      path: '/tuition'
      fullPath: '/spaces/career/tuition'
      preLoaderRoute: typeof SpacesCareerTuitionRouteImport
      parentRoute: typeof SpacesCareerRoute
    }
    '/spaces/career/resume-builder': {
      id: '/spaces/career/resume-builder'
      path: '/resume-builder'
      fullPath: '/spaces/career/resume-builder'
      preLoaderRoute: typeof SpacesCareerResumeBuilderRouteImport
      parentRoute: typeof SpacesCareerRoute
    }
    '/spaces/career/internship': {
      id: '/spaces/career/internship'
      path: '/internship'
      fullPath: '/spaces/career/internship'
      preLoaderRoute: typeof SpacesCareerInternshipRouteImport
      parentRoute: typeof SpacesCareerRoute
    }
    '/spaces/career/applications': {
      id: '/spaces/career/applications'
      path: '/applications'
      fullPath: '/spaces/career/applications'
      preLoaderRoute: typeof SpacesCareerApplicationsRouteImport
      parentRoute: typeof SpacesCareerRoute
    }
    '/spaces/academics/study-groups': {
      id: '/spaces/academics/study-groups'
      path: '/study-groups'
      fullPath: '/spaces/academics/study-groups'
      preLoaderRoute: typeof SpacesAcademicsStudyGroupsRouteImport
      parentRoute: typeof SpacesAcademicsRoute
    }
    '/spaces/academics/onboarding': {
      id: '/spaces/academics/onboarding'
      path: '/onboarding'
      fullPath: '/spaces/academics/onboarding'
      preLoaderRoute: typeof SpacesAcademicsOnboardingRouteImport
      parentRoute: typeof SpacesAcademicsRoute
    }
    '/spaces/academics/dashboard': {
      id: '/spaces/academics/dashboard'
      path: '/dashboard'
      fullPath: '/spaces/academics/dashboard'
      preLoaderRoute: typeof SpacesAcademicsDashboardRouteImport
      parentRoute: typeof SpacesAcademicsRoute
    }
    '/join/$societySlug/payment': {
      id: '/join/$societySlug/payment'
      path: '/payment'
      fullPath: '/join/$societySlug/payment'
      preLoaderRoute: typeof JoinSocietySlugPaymentRouteImport
      parentRoute: typeof JoinSocietySlugRoute
    }
    '/join/$societySlug/apply': {
      id: '/join/$societySlug/apply'
      path: '/apply'
      fullPath: '/join/$societySlug/apply'
      preLoaderRoute: typeof JoinSocietySlugApplyRouteImport
      parentRoute: typeof JoinSocietySlugRoute
    }
    '/apps/quera/build': {
      id: '/apps/quera/build'
      path: '/build'
      fullPath: '/apps/quera/build'
      preLoaderRoute: typeof AppsQueraBuildRouteImport
      parentRoute: typeof AppsQueraRoute
    }
    '/spaces/societies/mine/': {
      id: '/spaces/societies/mine/'
      path: '/'
      fullPath: '/spaces/societies/mine/'
      preLoaderRoute: typeof SpacesSocietiesMineIndexRouteImport
      parentRoute: typeof SpacesSocietiesMineRoute
    }
    '/spaces/societies/campus-feed/': {
      id: '/spaces/societies/campus-feed/'
      path: '/'
      fullPath: '/spaces/societies/campus-feed/'
      preLoaderRoute: typeof SpacesSocietiesCampusFeedIndexRouteImport
      parentRoute: typeof SpacesSocietiesCampusFeedRoute
    }
    '/spaces/societies/mine/$clubID': {
      id: '/spaces/societies/mine/$clubID'
      path: '/$clubID'
      fullPath: '/spaces/societies/mine/$clubID'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDRouteImport
      parentRoute: typeof SpacesSocietiesMineRoute
    }
    '/spaces/societies/discover/network': {
      id: '/spaces/societies/discover/network'
      path: '/discover/network'
      fullPath: '/spaces/societies/discover/network'
      preLoaderRoute: typeof SpacesSocietiesDiscoverNetworkRouteImport
      parentRoute: typeof SpacesSocietiesRoute
    }
    '/spaces/societies/discover/events': {
      id: '/spaces/societies/discover/events'
      path: '/discover/events'
      fullPath: '/spaces/societies/discover/events'
      preLoaderRoute: typeof SpacesSocietiesDiscoverEventsRouteImport
      parentRoute: typeof SpacesSocietiesRoute
    }
    '/spaces/societies/discover/browse-clubs': {
      id: '/spaces/societies/discover/browse-clubs'
      path: '/discover/browse-clubs'
      fullPath: '/spaces/societies/discover/browse-clubs'
      preLoaderRoute: typeof SpacesSocietiesDiscoverBrowseClubsRouteImport
      parentRoute: typeof SpacesSocietiesRoute
    }
    '/spaces/career/resume-builder/$resumeid': {
      id: '/spaces/career/resume-builder/$resumeid'
      path: '/$resumeid'
      fullPath: '/spaces/career/resume-builder/$resumeid'
      preLoaderRoute: typeof SpacesCareerResumeBuilderResumeidRouteImport
      parentRoute: typeof SpacesCareerResumeBuilderRoute
    }
    '/spaces/career/applications/$id': {
      id: '/spaces/career/applications/$id'
      path: '/$id'
      fullPath: '/spaces/career/applications/$id'
      preLoaderRoute: typeof SpacesCareerApplicationsIdRouteImport
      parentRoute: typeof SpacesCareerApplicationsRoute
    }
    '/spaces/academics/discover/study-groups': {
      id: '/spaces/academics/discover/study-groups'
      path: '/discover/study-groups'
      fullPath: '/spaces/academics/discover/study-groups'
      preLoaderRoute: typeof SpacesAcademicsDiscoverStudyGroupsRouteImport
      parentRoute: typeof SpacesAcademicsRoute
    }
    '/spaces/academics/discover/study-buddy': {
      id: '/spaces/academics/discover/study-buddy'
      path: '/discover/study-buddy'
      fullPath: '/spaces/academics/discover/study-buddy'
      preLoaderRoute: typeof SpacesAcademicsDiscoverStudyBuddyRouteImport
      parentRoute: typeof SpacesAcademicsRoute
    }
    '/spaces/academics/courses/$courseId': {
      id: '/spaces/academics/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/spaces/academics/courses/$courseId'
      preLoaderRoute: typeof SpacesAcademicsCoursesCourseIdRouteImport
      parentRoute: typeof SpacesAcademicsRoute
    }
    '/apps/quera/play/$id': {
      id: '/apps/quera/play/$id'
      path: '/play/$id'
      fullPath: '/apps/quera/play/$id'
      preLoaderRoute: typeof AppsQueraPlayIdRouteImport
      parentRoute: typeof AppsQueraRoute
    }
    '/spaces/societies/mine/$clubID/': {
      id: '/spaces/societies/mine/$clubID/'
      path: '/'
      fullPath: '/spaces/societies/mine/$clubID/'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDIndexRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/academics/courses/$courseId/': {
      id: '/spaces/academics/courses/$courseId/'
      path: '/'
      fullPath: '/spaces/academics/courses/$courseId/'
      preLoaderRoute: typeof SpacesAcademicsCoursesCourseIdIndexRouteImport
      parentRoute: typeof SpacesAcademicsCoursesCourseIdRoute
    }
    '/spaces/societies/mine/$clubID/teams': {
      id: '/spaces/societies/mine/$clubID/teams'
      path: '/teams'
      fullPath: '/spaces/societies/mine/$clubID/teams'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDTeamsRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/tasks': {
      id: '/spaces/societies/mine/$clubID/tasks'
      path: '/tasks'
      fullPath: '/spaces/societies/mine/$clubID/tasks'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDTasksRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/settings': {
      id: '/spaces/societies/mine/$clubID/settings'
      path: '/settings'
      fullPath: '/spaces/societies/mine/$clubID/settings'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDSettingsRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/onboarding': {
      id: '/spaces/societies/mine/$clubID/onboarding'
      path: '/onboarding'
      fullPath: '/spaces/societies/mine/$clubID/onboarding'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDOnboardingRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/members': {
      id: '/spaces/societies/mine/$clubID/members'
      path: '/members'
      fullPath: '/spaces/societies/mine/$clubID/members'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDMembersRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/join-requests': {
      id: '/spaces/societies/mine/$clubID/join-requests'
      path: '/join-requests'
      fullPath: '/spaces/societies/mine/$clubID/join-requests'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDJoinRequestsRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/forms': {
      id: '/spaces/societies/mine/$clubID/forms'
      path: '/forms'
      fullPath: '/spaces/societies/mine/$clubID/forms'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDFormsRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/expenses': {
      id: '/spaces/societies/mine/$clubID/expenses'
      path: '/expenses'
      fullPath: '/spaces/societies/mine/$clubID/expenses'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDExpensesRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/email': {
      id: '/spaces/societies/mine/$clubID/email'
      path: '/email'
      fullPath: '/spaces/societies/mine/$clubID/email'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDEmailRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/societies/mine/$clubID/discussion': {
      id: '/spaces/societies/mine/$clubID/discussion'
      path: '/discussion'
      fullPath: '/spaces/societies/mine/$clubID/discussion'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDDiscussionRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDRoute
    }
    '/spaces/academics/courses/$courseId/discussions': {
      id: '/spaces/academics/courses/$courseId/discussions'
      path: '/discussions'
      fullPath: '/spaces/academics/courses/$courseId/discussions'
      preLoaderRoute: typeof SpacesAcademicsCoursesCourseIdDiscussionsRouteImport
      parentRoute: typeof SpacesAcademicsCoursesCourseIdRoute
    }
    '/spaces/societies/mine/$clubID/forms/': {
      id: '/spaces/societies/mine/$clubID/forms/'
      path: '/'
      fullPath: '/spaces/societies/mine/$clubID/forms/'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDFormsIndexRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDFormsRoute
    }
    '/spaces/societies/mine/$clubID/join-requests/$requestId': {
      id: '/spaces/societies/mine/$clubID/join-requests/$requestId'
      path: '/$requestId'
      fullPath: '/spaces/societies/mine/$clubID/join-requests/$requestId'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDJoinRequestsRequestIdRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDJoinRequestsRoute
    }
    '/spaces/societies/mine/$clubID/forms/create': {
      id: '/spaces/societies/mine/$clubID/forms/create'
      path: '/create'
      fullPath: '/spaces/societies/mine/$clubID/forms/create'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDFormsCreateRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDFormsRoute
    }
    '/spaces/societies/mine/$clubID/forms/$formId': {
      id: '/spaces/societies/mine/$clubID/forms/$formId'
      path: '/$formId'
      fullPath: '/spaces/societies/mine/$clubID/forms/$formId'
      preLoaderRoute: typeof SpacesSocietiesMineClubIDFormsFormIdRouteImport
      parentRoute: typeof SpacesSocietiesMineClubIDFormsRoute
    }
  }
}

interface UsernameRouteChildren {
  UsernameIndexRoute: typeof UsernameIndexRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameIndexRoute: UsernameIndexRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

interface AppsQueraRouteChildren {
  AppsQueraBuildRoute: typeof AppsQueraBuildRoute
  AppsQueraIndexRoute: typeof AppsQueraIndexRoute
  AppsQueraPlayIdRoute: typeof AppsQueraPlayIdRoute
}

const AppsQueraRouteChildren: AppsQueraRouteChildren = {
  AppsQueraBuildRoute: AppsQueraBuildRoute,
  AppsQueraIndexRoute: AppsQueraIndexRoute,
  AppsQueraPlayIdRoute: AppsQueraPlayIdRoute,
}

const AppsQueraRouteWithChildren = AppsQueraRoute._addFileChildren(
  AppsQueraRouteChildren,
)

interface AppsRouteChildren {
  AppsQueraRoute: typeof AppsQueraRouteWithChildren
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsQueraRoute: AppsQueraRouteWithChildren,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

interface JoinSocietySlugRouteChildren {
  JoinSocietySlugApplyRoute: typeof JoinSocietySlugApplyRoute
  JoinSocietySlugPaymentRoute: typeof JoinSocietySlugPaymentRoute
  JoinSocietySlugIndexRoute: typeof JoinSocietySlugIndexRoute
}

const JoinSocietySlugRouteChildren: JoinSocietySlugRouteChildren = {
  JoinSocietySlugApplyRoute: JoinSocietySlugApplyRoute,
  JoinSocietySlugPaymentRoute: JoinSocietySlugPaymentRoute,
  JoinSocietySlugIndexRoute: JoinSocietySlugIndexRoute,
}

const JoinSocietySlugRouteWithChildren = JoinSocietySlugRoute._addFileChildren(
  JoinSocietySlugRouteChildren,
)

interface JoinRouteChildren {
  JoinSocietySlugRoute: typeof JoinSocietySlugRouteWithChildren
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinSocietySlugRoute: JoinSocietySlugRouteWithChildren,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

interface PeopleRouteChildren {
  PeoplePeopleRoute: typeof PeoplePeopleRoute
  PeopleRequestsRoute: typeof PeopleRequestsRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeoplePeopleRoute: PeoplePeopleRoute,
  PeopleRequestsRoute: PeopleRequestsRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface ProfileRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SpacesAcademicsCoursesCourseIdRouteChildren {
  SpacesAcademicsCoursesCourseIdDiscussionsRoute: typeof SpacesAcademicsCoursesCourseIdDiscussionsRoute
  SpacesAcademicsCoursesCourseIdIndexRoute: typeof SpacesAcademicsCoursesCourseIdIndexRoute
}

const SpacesAcademicsCoursesCourseIdRouteChildren: SpacesAcademicsCoursesCourseIdRouteChildren =
  {
    SpacesAcademicsCoursesCourseIdDiscussionsRoute:
      SpacesAcademicsCoursesCourseIdDiscussionsRoute,
    SpacesAcademicsCoursesCourseIdIndexRoute:
      SpacesAcademicsCoursesCourseIdIndexRoute,
  }

const SpacesAcademicsCoursesCourseIdRouteWithChildren =
  SpacesAcademicsCoursesCourseIdRoute._addFileChildren(
    SpacesAcademicsCoursesCourseIdRouteChildren,
  )

interface SpacesAcademicsRouteChildren {
  SpacesAcademicsDashboardRoute: typeof SpacesAcademicsDashboardRoute
  SpacesAcademicsOnboardingRoute: typeof SpacesAcademicsOnboardingRoute
  SpacesAcademicsStudyGroupsRoute: typeof SpacesAcademicsStudyGroupsRoute
  SpacesAcademicsIndexRoute: typeof SpacesAcademicsIndexRoute
  SpacesAcademicsCoursesCourseIdRoute: typeof SpacesAcademicsCoursesCourseIdRouteWithChildren
  SpacesAcademicsDiscoverStudyBuddyRoute: typeof SpacesAcademicsDiscoverStudyBuddyRoute
  SpacesAcademicsDiscoverStudyGroupsRoute: typeof SpacesAcademicsDiscoverStudyGroupsRoute
}

const SpacesAcademicsRouteChildren: SpacesAcademicsRouteChildren = {
  SpacesAcademicsDashboardRoute: SpacesAcademicsDashboardRoute,
  SpacesAcademicsOnboardingRoute: SpacesAcademicsOnboardingRoute,
  SpacesAcademicsStudyGroupsRoute: SpacesAcademicsStudyGroupsRoute,
  SpacesAcademicsIndexRoute: SpacesAcademicsIndexRoute,
  SpacesAcademicsCoursesCourseIdRoute:
    SpacesAcademicsCoursesCourseIdRouteWithChildren,
  SpacesAcademicsDiscoverStudyBuddyRoute:
    SpacesAcademicsDiscoverStudyBuddyRoute,
  SpacesAcademicsDiscoverStudyGroupsRoute:
    SpacesAcademicsDiscoverStudyGroupsRoute,
}

const SpacesAcademicsRouteWithChildren = SpacesAcademicsRoute._addFileChildren(
  SpacesAcademicsRouteChildren,
)

interface SpacesCareerApplicationsRouteChildren {
  SpacesCareerApplicationsIdRoute: typeof SpacesCareerApplicationsIdRoute
}

const SpacesCareerApplicationsRouteChildren: SpacesCareerApplicationsRouteChildren =
  {
    SpacesCareerApplicationsIdRoute: SpacesCareerApplicationsIdRoute,
  }

const SpacesCareerApplicationsRouteWithChildren =
  SpacesCareerApplicationsRoute._addFileChildren(
    SpacesCareerApplicationsRouteChildren,
  )

interface SpacesCareerResumeBuilderRouteChildren {
  SpacesCareerResumeBuilderResumeidRoute: typeof SpacesCareerResumeBuilderResumeidRoute
}

const SpacesCareerResumeBuilderRouteChildren: SpacesCareerResumeBuilderRouteChildren =
  {
    SpacesCareerResumeBuilderResumeidRoute:
      SpacesCareerResumeBuilderResumeidRoute,
  }

const SpacesCareerResumeBuilderRouteWithChildren =
  SpacesCareerResumeBuilderRoute._addFileChildren(
    SpacesCareerResumeBuilderRouteChildren,
  )

interface SpacesCareerRouteChildren {
  SpacesCareerApplicationsRoute: typeof SpacesCareerApplicationsRouteWithChildren
  SpacesCareerInternshipRoute: typeof SpacesCareerInternshipRoute
  SpacesCareerResumeBuilderRoute: typeof SpacesCareerResumeBuilderRouteWithChildren
  SpacesCareerTuitionRoute: typeof SpacesCareerTuitionRoute
  SpacesCareerIndexRoute: typeof SpacesCareerIndexRoute
}

const SpacesCareerRouteChildren: SpacesCareerRouteChildren = {
  SpacesCareerApplicationsRoute: SpacesCareerApplicationsRouteWithChildren,
  SpacesCareerInternshipRoute: SpacesCareerInternshipRoute,
  SpacesCareerResumeBuilderRoute: SpacesCareerResumeBuilderRouteWithChildren,
  SpacesCareerTuitionRoute: SpacesCareerTuitionRoute,
  SpacesCareerIndexRoute: SpacesCareerIndexRoute,
}

const SpacesCareerRouteWithChildren = SpacesCareerRoute._addFileChildren(
  SpacesCareerRouteChildren,
)

interface SpacesSocietiesCampusFeedRouteChildren {
  SpacesSocietiesCampusFeedIndexRoute: typeof SpacesSocietiesCampusFeedIndexRoute
}

const SpacesSocietiesCampusFeedRouteChildren: SpacesSocietiesCampusFeedRouteChildren =
  {
    SpacesSocietiesCampusFeedIndexRoute: SpacesSocietiesCampusFeedIndexRoute,
  }

const SpacesSocietiesCampusFeedRouteWithChildren =
  SpacesSocietiesCampusFeedRoute._addFileChildren(
    SpacesSocietiesCampusFeedRouteChildren,
  )

interface SpacesSocietiesMineClubIDFormsRouteChildren {
  SpacesSocietiesMineClubIDFormsFormIdRoute: typeof SpacesSocietiesMineClubIDFormsFormIdRoute
  SpacesSocietiesMineClubIDFormsCreateRoute: typeof SpacesSocietiesMineClubIDFormsCreateRoute
  SpacesSocietiesMineClubIDFormsIndexRoute: typeof SpacesSocietiesMineClubIDFormsIndexRoute
}

const SpacesSocietiesMineClubIDFormsRouteChildren: SpacesSocietiesMineClubIDFormsRouteChildren =
  {
    SpacesSocietiesMineClubIDFormsFormIdRoute:
      SpacesSocietiesMineClubIDFormsFormIdRoute,
    SpacesSocietiesMineClubIDFormsCreateRoute:
      SpacesSocietiesMineClubIDFormsCreateRoute,
    SpacesSocietiesMineClubIDFormsIndexRoute:
      SpacesSocietiesMineClubIDFormsIndexRoute,
  }

const SpacesSocietiesMineClubIDFormsRouteWithChildren =
  SpacesSocietiesMineClubIDFormsRoute._addFileChildren(
    SpacesSocietiesMineClubIDFormsRouteChildren,
  )

interface SpacesSocietiesMineClubIDJoinRequestsRouteChildren {
  SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute: typeof SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute
}

const SpacesSocietiesMineClubIDJoinRequestsRouteChildren: SpacesSocietiesMineClubIDJoinRequestsRouteChildren =
  {
    SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute:
      SpacesSocietiesMineClubIDJoinRequestsRequestIdRoute,
  }

const SpacesSocietiesMineClubIDJoinRequestsRouteWithChildren =
  SpacesSocietiesMineClubIDJoinRequestsRoute._addFileChildren(
    SpacesSocietiesMineClubIDJoinRequestsRouteChildren,
  )

interface SpacesSocietiesMineClubIDRouteChildren {
  SpacesSocietiesMineClubIDDiscussionRoute: typeof SpacesSocietiesMineClubIDDiscussionRoute
  SpacesSocietiesMineClubIDEmailRoute: typeof SpacesSocietiesMineClubIDEmailRoute
  SpacesSocietiesMineClubIDExpensesRoute: typeof SpacesSocietiesMineClubIDExpensesRoute
  SpacesSocietiesMineClubIDFormsRoute: typeof SpacesSocietiesMineClubIDFormsRouteWithChildren
  SpacesSocietiesMineClubIDJoinRequestsRoute: typeof SpacesSocietiesMineClubIDJoinRequestsRouteWithChildren
  SpacesSocietiesMineClubIDMembersRoute: typeof SpacesSocietiesMineClubIDMembersRoute
  SpacesSocietiesMineClubIDOnboardingRoute: typeof SpacesSocietiesMineClubIDOnboardingRoute
  SpacesSocietiesMineClubIDSettingsRoute: typeof SpacesSocietiesMineClubIDSettingsRoute
  SpacesSocietiesMineClubIDTasksRoute: typeof SpacesSocietiesMineClubIDTasksRoute
  SpacesSocietiesMineClubIDTeamsRoute: typeof SpacesSocietiesMineClubIDTeamsRoute
  SpacesSocietiesMineClubIDIndexRoute: typeof SpacesSocietiesMineClubIDIndexRoute
}

const SpacesSocietiesMineClubIDRouteChildren: SpacesSocietiesMineClubIDRouteChildren =
  {
    SpacesSocietiesMineClubIDDiscussionRoute:
      SpacesSocietiesMineClubIDDiscussionRoute,
    SpacesSocietiesMineClubIDEmailRoute: SpacesSocietiesMineClubIDEmailRoute,
    SpacesSocietiesMineClubIDExpensesRoute:
      SpacesSocietiesMineClubIDExpensesRoute,
    SpacesSocietiesMineClubIDFormsRoute:
      SpacesSocietiesMineClubIDFormsRouteWithChildren,
    SpacesSocietiesMineClubIDJoinRequestsRoute:
      SpacesSocietiesMineClubIDJoinRequestsRouteWithChildren,
    SpacesSocietiesMineClubIDMembersRoute:
      SpacesSocietiesMineClubIDMembersRoute,
    SpacesSocietiesMineClubIDOnboardingRoute:
      SpacesSocietiesMineClubIDOnboardingRoute,
    SpacesSocietiesMineClubIDSettingsRoute:
      SpacesSocietiesMineClubIDSettingsRoute,
    SpacesSocietiesMineClubIDTasksRoute: SpacesSocietiesMineClubIDTasksRoute,
    SpacesSocietiesMineClubIDTeamsRoute: SpacesSocietiesMineClubIDTeamsRoute,
    SpacesSocietiesMineClubIDIndexRoute: SpacesSocietiesMineClubIDIndexRoute,
  }

const SpacesSocietiesMineClubIDRouteWithChildren =
  SpacesSocietiesMineClubIDRoute._addFileChildren(
    SpacesSocietiesMineClubIDRouteChildren,
  )

interface SpacesSocietiesMineRouteChildren {
  SpacesSocietiesMineClubIDRoute: typeof SpacesSocietiesMineClubIDRouteWithChildren
  SpacesSocietiesMineIndexRoute: typeof SpacesSocietiesMineIndexRoute
}

const SpacesSocietiesMineRouteChildren: SpacesSocietiesMineRouteChildren = {
  SpacesSocietiesMineClubIDRoute: SpacesSocietiesMineClubIDRouteWithChildren,
  SpacesSocietiesMineIndexRoute: SpacesSocietiesMineIndexRoute,
}

const SpacesSocietiesMineRouteWithChildren =
  SpacesSocietiesMineRoute._addFileChildren(SpacesSocietiesMineRouteChildren)

interface SpacesSocietiesRouteChildren {
  SpacesSocietiesCampusFeedRoute: typeof SpacesSocietiesCampusFeedRouteWithChildren
  SpacesSocietiesCreateRoute: typeof SpacesSocietiesCreateRoute
  SpacesSocietiesMineRoute: typeof SpacesSocietiesMineRouteWithChildren
  SpacesSocietiesIndexRoute: typeof SpacesSocietiesIndexRoute
  SpacesSocietiesDiscoverBrowseClubsRoute: typeof SpacesSocietiesDiscoverBrowseClubsRoute
  SpacesSocietiesDiscoverEventsRoute: typeof SpacesSocietiesDiscoverEventsRoute
  SpacesSocietiesDiscoverNetworkRoute: typeof SpacesSocietiesDiscoverNetworkRoute
}

const SpacesSocietiesRouteChildren: SpacesSocietiesRouteChildren = {
  SpacesSocietiesCampusFeedRoute: SpacesSocietiesCampusFeedRouteWithChildren,
  SpacesSocietiesCreateRoute: SpacesSocietiesCreateRoute,
  SpacesSocietiesMineRoute: SpacesSocietiesMineRouteWithChildren,
  SpacesSocietiesIndexRoute: SpacesSocietiesIndexRoute,
  SpacesSocietiesDiscoverBrowseClubsRoute:
    SpacesSocietiesDiscoverBrowseClubsRoute,
  SpacesSocietiesDiscoverEventsRoute: SpacesSocietiesDiscoverEventsRoute,
  SpacesSocietiesDiscoverNetworkRoute: SpacesSocietiesDiscoverNetworkRoute,
}

const SpacesSocietiesRouteWithChildren = SpacesSocietiesRoute._addFileChildren(
  SpacesSocietiesRouteChildren,
)

interface SpacesRouteChildren {
  SpacesAcademicsRoute: typeof SpacesAcademicsRouteWithChildren
  SpacesCareerRoute: typeof SpacesCareerRouteWithChildren
  SpacesPersonalRoute: typeof SpacesPersonalRoute
  SpacesSocialRoute: typeof SpacesSocialRoute
  SpacesSocietiesRoute: typeof SpacesSocietiesRouteWithChildren
  SpacesIndexRoute: typeof SpacesIndexRoute
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesAcademicsRoute: SpacesAcademicsRouteWithChildren,
  SpacesCareerRoute: SpacesCareerRouteWithChildren,
  SpacesPersonalRoute: SpacesPersonalRoute,
  SpacesSocialRoute: SpacesSocialRoute,
  SpacesSocietiesRoute: SpacesSocietiesRouteWithChildren,
  SpacesIndexRoute: SpacesIndexRoute,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRouteWithChildren,
  AppsRoute: AppsRouteWithChildren,
  JoinRoute: JoinRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  PeopleRoute: PeopleRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  SignupRoute: SignupRoute,
  SpacesRoute: SpacesRouteWithChildren,
  TermsAndServiceRoute: TermsAndServiceRoute,
  SocietiesSocietyIdRoute: SocietiesSocietyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
